services:
  # Reverse Proxy for Security
  nginx-proxy:
    image: nginx:alpine
    container_name: brain-blog-proxy
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./config/ssl:/etc/nginx/ssl:ro
    depends_on:
      - braincargo-blog-service
    networks:
      - brain-blog-internal
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    
  braincargo-blog-service:
    image: braincargo/brain-blog:latest
    container_name: brain-blog
    # Security: No external port exposure - only accessible via reverse proxy
    expose:
      - "8080"
    volumes:
      # User configuration
      - ./config/.env:/app/config/.env:ro
      - ./config/pipeline.yaml:/app/config/pipeline.yaml:ro
      
      # Custom prompts (optional - defaults included in image)
      - ./prompts:/app/prompts:ro
      
      # Vector store documents for knowledge base
      - ./vector_store_docs:/app/vector_store_docs:ro
      
      # Vector store manifests (persistent)
      - ./openai_store:/app/openai_store
      
      # Output directory for generated blogs
      - ./output:/app/local_output
      
    environment:
      - PYTHONPATH=/app
      - ENVIRONMENT=production
      - RATE_LIMIT_ENABLED=true
      - API_KEY_REQUIRED=true
      
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
      
    restart: unless-stopped
    
    # Security: Ensure proper file permissions and capabilities
    user: "1000:1000"
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    networks:
      - brain-blog-internal

networks:
  brain-blog-internal:
    driver: bridge
    internal: false
    ipam:
      config:
        - subnet: 172.20.0.0/16
