# BrainCargo Blog Service Pipeline Configuration Example
# Copy this file to pipeline.yaml and customize as needed

# Provider configurations with fallback hierarchy
providers:
  openai:
    type: openai
    api_key_env: OPENAI_API_KEY
    models:
      fast: gpt-4o-mini
      standard: gpt-4o
      creative: gpt-4o
    default_temperature: 0.7
    max_tokens: 4000
    timeout: 120

  anthropic:
    type: anthropic
    api_key_env: ANTHROPIC_API_KEY
    models:
      fast: claude-3-5-haiku-20241022
      standard: claude-3-5-sonnet-20241022
      creative: claude-3-5-sonnet-20241022
    default_temperature: 0.7
    max_tokens: 4000
    timeout: 120

  grok:
    type: grok
    api_key_env: GROK_API_KEY
    models:
      fast: grok-beta
      standard: grok-beta
      creative: grok-beta
    default_temperature: 0.8
    max_tokens: 4000
    timeout: 120

  gemini:
    type: gemini
    api_key_env: GEMINI_API_KEY
    models:
      fast: gemini-1.5-flash
      standard: gemini-1.5-pro
      creative: gemini-1.5-pro
    default_temperature: 0.7
    max_tokens: 4000
    timeout: 120

# Vector stores configuration for knowledge enhancement
vector_stores:
  enabled: true
  openai:
    enabled: true
    vector_store_ids: "${OPENAI_VECTOR_STORE_IDS}"
    manifest_file: "openai_store/openai_vector_store.json"
    auto_detect: true
  anthropic:
    enabled: true
    file_ids: "${ANTHROPIC_FILE_IDS}"
    manifest_file: "openai_store/anthropic_uploads.json"
    auto_detect: true
  usage:
    blog_generation: true     # Use knowledge for enhanced content
    categorization: false     # Keep categorization fast
    image_generation: false   # Keep image prompts creative
    meme_generation: false    # Keep memes spontaneous

# Pipeline stage configurations
blog_generation:
  primary_provider: openai
  fallback_providers: [anthropic, grok, gemini]
  use_knowledge: true
  style_personas:
    - security
    - technology
    - web3
  default_style: technology

categorization:
  primary_provider: openai
  fallback_providers: [anthropic]
  use_knowledge: false

image_generation:
  enabled: true
  primary_provider: openai
  fallback_providers: []
  use_knowledge: false
  image_model: dall-e-3
  size: "1792x1024"
  quality: hd

meme_generation:
  enabled: true
  primary_provider: openai
  fallback_providers: [anthropic]
  use_knowledge: false

# Media storage configuration
media_storage:
  enabled: true
  bucket_env: BLOG_POSTS_BUCKET
  local_fallback: true
  local_directory: local_output

# Rate limiting and performance
rate_limiting:
  enabled: true
  requests_per_minute: 60
  burst_limit: 10

# Monitoring and health checks
monitoring:
  enabled: true
  health_check_interval: 30
  log_level: INFO
  metrics_enabled: false

# Output settings
output:
  format: json
  include_debug_info: false
  save_to_file: true 